# Generated by Django 4.2.8 on 2023-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_remove_fieldstypes_field_re_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldstypes",
            name="name",
            field=models.CharField(
                choices=[
                    ("ИНН", "ИНН"),
                    ("ФИО", "ФИО"),
                    ("Адрес", "Адрес"),
                    ("ОГРН", "ОГРН"),
                ],
                help_text="Название поля формы",
                max_length=50,
            ),
        ),
    ]
