# Generated by Django 4.2.8 on 2024-02-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stamp_fields", "0001_initial"),
        ("mainapp", "0010_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupoffieldstypes",
            name="fields",
        ),
        migrations.AlterField(
            model_name="stamp",
            name="fields",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="stamp_fields.groupoffieldstypes",
                verbose_name="Набор полей",
            ),
        ),
        migrations.DeleteModel(
            name="FieldsTypes",
        ),
        migrations.DeleteModel(
            name="GroupOfFieldsTypes",
        ),
    ]
