# Generated by Django 4.2.8 on 2024-02-18 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainapp",
            "0011_remove_groupoffieldstypes_fields_alter_stamp_fields_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stamp",
            old_name="fields",
            new_name="form_fields",
        ),
    ]
