# Generated by Django 4.2.11 on 2024-04-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stamp_fields", "0002_alter_fieldstypes_options_and_more"),
        ("mainapp", "0012_rename_fields_stamp_form_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stamp",
            name="form_fields",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="stamps",
                to="stamp_fields.groupoffieldstypes",
                verbose_name="Набор полей",
            ),
        ),
    ]
