repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false
        args: ["--verbose"]

      - id: black
        name: black
        entry: black --config ./pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false
        args: ["--verbose"]

      - id: flake8
        name: flake8
        entry: flake8 --config setup.cfg .
        language: system
        types: [ python ]
        pass_filenames: false
        args: ["--verbose"]

      - id: django-tests
        name: Django Tests
        entry: bash scripts/run_tests.sh
        language: system
        verbose: true

      - id: django-migrations
        name: Django Migrations
        entry: bash scripts/check_migrations.sh
        language: system
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: name-tests-test
        args: ["--django"]
      - id: mixed-line-ending
        args: ["--fix=auto"]

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
