# Generated by Django 4.2.6 on 2023-12-14 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printy",
            options={
                "ordering": ("-updated",),
                "verbose_name": "Оснастка",
                "verbose_name_plural": "Оснастки",
            },
        ),
        migrations.AlterModelOptions(
            name="printygroup",
            options={
                "ordering": ("-updated",),
                "verbose_name": "Группа оснасток",
                "verbose_name_plural": "Группы оснасток",
            },
        ),
    ]
