# Generated by Django 4.2.6 on 2023-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printy", "0002_alter_printy_options_alter_printygroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printy",
            name="slug",
            field=models.SlugField(
                help_text="Уникальный текстовый идентификатор группы",
                unique=True,
            ),
        ),
    ]
