# It's a part of the base compose file.
# It adds and overrides some settings of the base file to make it work for development.
# "docker compose up" will use both compose.yml and compose.override.yml automatically.
name: stamps-dev

services:
  rabbitmq:
    ports:
      - 5672:5672
