# Generated by Django 4.2.6 on 2023-12-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printy", "0002_alter_printy_options_alter_printygroup_options"),
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stamp",
            options={
                "ordering": ("-updated",),
                "verbose_name": "Печать",
                "verbose_name_plural": "Печати",
            },
        ),
        migrations.AlterModelOptions(
            name="stampgroup",
            options={
                "ordering": ("-updated",),
                "verbose_name": "Группа печатей",
                "verbose_name_plural": "Группы печатей",
            },
        ),
        migrations.AlterField(
            model_name="stamp",
            name="printy",
            field=models.ManyToManyField(
                error_messages="Печать должна быть привязанна хотя бы к одной оснастке.",
                help_text="Оснастки доступные для этой печати",
                related_name="printy",
                to="printy.printy",
                verbose_name="Оснастка",
            ),
        ),
    ]
