# Generated by Django 4.2.8 on 2023-12-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldstypes",
            name="field_re",
        ),
        migrations.RemoveField(
            model_name="fieldstypes",
            name="field_type",
        ),
        migrations.AddField(
            model_name="fieldstypes",
            name="help_text",
            field=models.CharField(
                default=1, help_text="Подпись под полем", max_length=150
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldstypes",
            name="name",
            field=models.CharField(
                choices=[("INN", "ИНН"), ("FIO", "ФИО"), ("ADDRESS", "Адрес")],
                default=1,
                help_text="Название поля формы",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldstypes",
            name="re",
            field=models.CharField(
                blank=True,
                help_text="Регулярное выражение для валидации",
                max_length=100,
            ),
        ),
    ]
