# Generated by Django 4.2.6 on 2023-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainapp",
            "0002_alter_stamp_options_alter_stampgroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stamp",
            name="slug",
            field=models.SlugField(
                help_text="Уникальный текстовый идентификатор группы",
                unique=True,
            ),
        ),
    ]
