# Generated by Django 4.2.3 on 2023-07-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_stamp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='group',
            field=models.ForeignKey(help_text='Группа, к которой будет относиться штамп', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamps', to='mainapp.group', verbose_name='Группа'),
        ),
    ]
