# Generated by Django 4.2.3 on 2023-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_stamp_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default=1, help_text='Загрузить картинку', upload_to='group_pics/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
