# Generated by Django 4.2.8 on 2024-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printy", "0002_alter_printy_group_alter_printy_published_and_more"),
        ("mainapp", "0005_alter_fieldstypes_options_fieldstypes_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldstypes",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="fieldstypes",
            name="help_text",
            field=models.CharField(
                max_length=150, verbose_name="Подпись под полем"
            ),
        ),
        migrations.AlterField(
            model_name="fieldstypes",
            name="name",
            field=models.CharField(
                choices=[
                    ("ИНН", "ИНН"),
                    ("ФИО", "ФИО"),
                    ("Адрес", "Адрес"),
                    ("ОГРН", "ОГРН"),
                ],
                max_length=50,
                verbose_name="Поле",
            ),
        ),
        migrations.AlterField(
            model_name="fieldstypes",
            name="re",
            field=models.CharField(
                blank=True,
                help_text="Дополнительная валидация через регулярное выражение",
                max_length=100,
                verbose_name="Регулярное выражение",
            ),
        ),
        migrations.AlterField(
            model_name="groupoffieldstypes",
            name="fields",
            field=models.ManyToManyField(
                to="mainapp.fieldstypes", verbose_name="Поля"
            ),
        ),
        migrations.AlterField(
            model_name="groupoffieldstypes",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название группы"
            ),
        ),
        migrations.AlterField(
            model_name="stamp",
            name="printy",
            field=models.ManyToManyField(
                error_messages="Печать должна быть привязана хотя бы к одной оснастке.",
                help_text="Оснастки доступные для этой печати",
                related_name="printy",
                to="printy.printy",
                verbose_name="Оснастка",
            ),
        ),
        migrations.AlterField(
            model_name="stamp",
            name="published",
            field=models.BooleanField(
                help_text="Включение и выключение отображение на сайте",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="stampgroup",
            name="published",
            field=models.BooleanField(
                help_text="Включение и выключение отображения на сайте",
                verbose_name="Опубликовано",
            ),
        ),
    ]
