# Generated by Django 4.2.3 on 2023-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_stamp_group_stamp_unique_title_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stamp',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
