# Generated by Django 4.2.8 on 2024-02-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("printy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printy",
            name="group",
            field=models.ForeignKey(
                help_text="Группа, к которой будет относиться оснастка",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="printy",
                to="printy.printygroup",
                verbose_name="Группа оснасток",
            ),
        ),
        migrations.AlterField(
            model_name="printy",
            name="published",
            field=models.BooleanField(
                help_text="Включение и выключение отображение на сайте",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="printygroup",
            name="published",
            field=models.BooleanField(
                help_text="Включение и выключение отображения на сайте",
                verbose_name="Опубликовано",
            ),
        ),
    ]
