#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd src
python manage.py makemigrations
python manage.py migrate
output=$(python manage.py createsuperuser --noinput 2>&1) || true
echo "$output"
celery -A config worker -l INFO &
exec python manage.py runserver 0.0.0.0:8000
