# Generated by Django 4.2.8 on 2023-12-19 15:10

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contacts",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Контакты"
                    ),
                ),
                (
                    "links",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Ссылки"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        help_text="Включение и выключение отображения на сайте",
                        verbose_name="Опубликованно",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="ContactYandexMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("map", models.TextField()),
                ("published", models.BooleanField()),
            ],
        ),
    ]
