# Generated by Django 4.2.6 on 2023-10-14 20:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contants",
                    ckeditor.fields.RichTextField(verbose_name="Контакты"),
                ),
                (
                    "links",
                    ckeditor.fields.RichTextField(verbose_name="Ссылки"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
