# Generated by Django 4.2.6 on 2023-10-14 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_rename_about_contacts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contact",
        ),
    ]
