# Generated by Django 4.2.6 on 2023-10-14 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_rename_contacts_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactAddress",
        ),
        migrations.DeleteModel(
            name="ContactEmail",
        ),
        migrations.DeleteModel(
            name="ContactMessage",
        ),
        migrations.DeleteModel(
            name="ContactPhone",
        ),
        migrations.DeleteModel(
            name="ContactSocial",
        ),
        migrations.DeleteModel(
            name="ContactTelegram",
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name_plural": "Контакты"},
        ),
    ]
