# Generated by Django 4.2.6 on 2023-10-15 14:15

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0006_delete_contactaddress_delete_contactemail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="published",
            field=models.BooleanField(
                default=1,
                help_text="Включение и выключение отображения на сайте",
                verbose_name="Опубликованно",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="contants",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Контакты"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="links",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Ссылки"
            ),
        ),
    ]
