# Generated by Django 4.2.6 on 2023-10-15 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0007_contact_published_alter_contact_contants_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="contants",
            new_name="contacts",
        ),
    ]
