# Generated by Django 4.2.8 on 2024-02-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldsTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Поле")),
                (
                    "re",
                    models.CharField(
                        blank=True,
                        help_text="Дополнительная валидация через регулярное выражение",
                        max_length=100,
                        verbose_name="Регулярное выражение",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        max_length=150, verbose_name="Подпись под полем"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип поля формы",
                "verbose_name_plural": "Типы полей формы",
                "ordering": ("-updated",),
            },
        ),
        migrations.CreateModel(
            name="GroupOfFieldsTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название группы"
                    ),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        to="stamp_fields.fieldstypes", verbose_name="Поля"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа типов полей",
                "verbose_name_plural": "Группы типов полей",
                "ordering": ("-updated",),
            },
        ),
    ]
